# ============================================================
# CI - étapes 1 : Tests automatiques uniquement (CI simple)
# ============================================================

name: CI - étapes 1 (test uniquement)

#region Déclencheurs du workflows
on:
  # Exécuter la CI à chaque PR vers le main
  pull_request:
    branches: [main]

  # Exécuter la CI à chaque push directe sur le main
  push:
    branches: [main]

  # Lancement manuel depuis l'interface GitHub Actions
  workflow_dispatch:
#endregion

#region Permissions minimales
permissions: {}
#endregion

#region Définition des jobs
jobs:
  ci_pipeline:
    runs-on: ubuntu-latest  # Runner Ubuntu GitHub

    steps:
      #region Étape 1 - Récupération du code source
      - name: Checkout du code
        uses: actions/checkout@v4
        # Récupère l'état du dépôt au SHA de la PR/push
      #endregion

      #region Étape 2 - Installation de Python
      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Adapter la version à celle utilisée par ton projet
      #endregion

      #region Étape 3 - Installation des dépendances
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # ⚠️ Le fichier doit inclure pytest
      #endregion

      #region Étape 4 - Exécution des tests unitaires
      - name: Lancer les tests unitaires
        run: |
          export PYTHONPATH=.
          pytest -v
      #endregion
#endregion
